version: '3.9'

services:
  backend:
    build: ./backend
    container_name: PiTunes-backend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=pitunes_db;Username=pitunes;Password=pitunes_pw
    volumes:
      - ./backend/song_cache:/app/song_cache
      - /etc/asound.conf:/etc/asound.conf
    ports:
      - "5219:80"
    depends_on:
      - frontend
      - postgres
    networks:
      - PiTunes-net
#    devices:
#      - /dev/snd

  frontend:
    build: ./frontend
    container_name: PiTunes-frontend
    restart: always
    ports:
      - "4200:80"
    networks:
      - PiTunes-net

  postgres:
    image: postgres:15
    container_name: PiTunes-postgres
    restart: always
    environment:
      POSTGRES_USER: pitunes
      POSTGRES_PASSWORD: pitunes_pw
      POSTGRES_DB: pitunes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - PiTunes-net

volumes:
  postgres-data:

networks:
  PiTunes-net:
    driver: bridge
